#define FLOW_TAP_TERM 125
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 230

#define PERMISSIVE_HOLD

#define COMBO_TERM 35

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "emVdK/GGRDBR"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 2

#define TAPPING_TERM_PER_KEY
#define NAVIGATOR_SCROLL_DIVIDER 50

#define NAVIGATOR_TRACKBALL_ROTATION 325
#define NAVIGATOR_TRACKPAD_ROTATION 35
#define AUTOMOUSE_LAYER 3
#define AUTOMOUSE_TIMEOUT 620
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define AUTOMOUSE_TIMEOUT_TRACKBALL 620
#define AUTOMOUSE_ONESHOT_TRACKBALL false
#define AUTOMOUSE_ONESHOT_TRACKPAD false
#define RGB_MATRIX_STARTUP_SPD 60

